version: '3.8'

services:
  # 데이터베이스 서비스 설정
  uichan-db:
    image: postgres:15
    container_name: uichan-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ~/pgdata:/var/lib/postgresql/data
    networks:
      - uichan-net
    restart: always

  # FastAPI 앱 서비스 설정
  fastapi-app:
    image: ${DOCKERHUB_USERNAME}/cicd-test:latest
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@uichan-db:5432/${DB_NAME}
      APP_MESSAGE: ${APP_MESSAGE}
    depends_on:
      - uichan-db  # DB가 먼저 실행되어야 함
    networks:
      - uichan-net
    restart: always

networks:
  uichan-net:
    driver: bridge